Changing scripts

diff --git a/.github/workflows/deploy-infra.yml b/.github/workflows/deploy-infra.yml
--- a/.github/workflows/deploy-infra.yml
+++ b/.github/workflows/deploy-infra.yml
@@ -55,8 +55,25 @@ jobs:
 
       - name: Terraform Plan
         id: plan
-        run: terraform plan -no-color -var-file="./tfvars/terraform.tfvars" -out main.tfplan
-        continue-on-error: true
+        run: |
+          export exitcode=0
+          terraform plan -no-color -var-file="./tfvars/terraform.tfvars" -out main.tfplan || export exitcode=$?
+
+          echo "exitcode=$exitcode" >> $GITHUB_OUTPUT
+
+          if [ $exitcode -eq 1 ]; then
+            echo "Error: Terraform plan failed"
+            exit 1
+          else
+            echo "Terraform plan was successful"
+            exit 0
+          fi
+        
+      - name: Publish Terraform Plan
+        uses: actions/upload-artifact@v4
+        with:
+          name: main.tfplan
+          path: main.tfplan
 
       - name: Update Pull Request
         uses: actions/github-script@v6
@@ -90,12 +107,6 @@ jobs:
       - name: Terraform Plan Status
         if: steps.plan.outcome == 'failure'
         run: exit 1
-
-      - name: Publish Terraform Plan
-        uses: actions/upload-artifact@v4
-        with:
-          name: main.tfplan
-          path: main.tfplan
 
       - name: Create String Output
         id: tf-plan-string
@@ -145,4 +156,4 @@ jobs:
           name: main.tfplan
 
       - name: Terraform Apply
-        run: terraform apply -no-color main.tfplan
+        run: terraform apply -auto-approve main.tfplan
